import type { LanguageCode } from '../types';
import type { VisualI18nKey } from './visualI18nSources';

type Map = Partial<Record<VisualI18nKey, string>>;

export const visualI18nExtraTargets: Partial<Record<LanguageCode, Map>> = {
  pt: { requestReview:'Solicitação em revisão', requestReviewText:'Quando o negócio confirmar a ativação, o app mudará em tempo real.', requestSent:'Solicitação enviada. O negócio poderá ativar seu Plus.', needHelp:'Preciso de ajuda', month:'/ mês', liveIndicators:'Indicadores ao vivo de atividade e pedidos da La Casa del Pollazo.', editingAddress:'Editando endereço', gpsOutside:'Seu GPS está fora de Puerto Ayora', confirmAddress:'Confirmar endereço', localSupport:'Suporte local', supportSubtitle:'Pedidos, pagamentos, entregas, promoções e conta.', faqReceived:'Como sei se meu pedido foi recebido?', faqPayments:'Pagamentos', faqCoupons:'Cupons e promoções', faqDelivery:'Entregas e cobertura', photoGallery:'Galeria fotográfica', premiumColdCuts:'Embutidos premium', firstGoal:'Sua primeira meta é registrar compras reais de 0 a 24 pontos.', pollazoFan:'Fã Pollazo', fromZero:'Desde 0', from25:'De 25 a 59 pontos', currentStatus:'Status atual', checkingLocal:'O local está verificando disponibilidade, localização e forma de pagamento.', time:'Tempo', freePlusPayment:'Pagamento grátis Plus', flour:'Farinhas', grains:'Grãos', rice:'Arroz', wholeChicken:'Frango inteiro', menudencia:'Miúdos' },
  fr: { requestReview:'Demande en révision', requestReviewText:'Quand le commerce confirme l’activation, l’app se met à jour en temps réel.', requestSent:'Demande envoyée. Le commerce pourra activer votre Plus.', needHelp:'J’ai besoin d’aide', month:'/ mois', liveIndicators:'Indicateurs en direct d’activité et de commandes de La Casa del Pollazo.', editingAddress:'Modification de l’adresse', gpsOutside:'Votre GPS est hors de Puerto Ayora', confirmAddress:'Confirmer l’adresse', localSupport:'Support local', supportSubtitle:'Commandes, paiements, livraisons, promotions et compte.', faqReceived:'Comment savoir si ma commande a été reçue ?', faqPayments:'Paiements', faqCoupons:'Coupons et promotions', faqDelivery:'Livraisons et couverture', photoGallery:'Galerie photo', premiumColdCuts:'Charcuterie premium', firstGoal:'Votre premier objectif est d’enregistrer des achats réels de 0 à 24 points.', pollazoFan:'Fan Pollazo', fromZero:'Dès 0', from25:'De 25 à 59 points', currentStatus:'Statut actuel', checkingLocal:'Le commerce vérifie la disponibilité, l’adresse et le mode de paiement.', time:'Temps', freePlusPayment:'Paiement gratuit Plus', flour:'Farines', grains:'Grains', rice:'Riz', wholeChicken:'Poulet entier', menudencia:'Abats' },
  de: { requestReview:'Anfrage wird geprüft', requestReviewText:'Wenn das Geschäft die Aktivierung bestätigt, aktualisiert sich die App in Echtzeit.', requestSent:'Anfrage gesendet. Das Geschäft kann dein Plus aktivieren.', needHelp:'Ich brauche Hilfe', month:'/ Monat', liveIndicators:'Live-Anzeigen für Aktivität und Bestellungen von La Casa del Pollazo.', editingAddress:'Adresse bearbeiten', gpsOutside:'Dein GPS ist außerhalb von Puerto Ayora', confirmAddress:'Adresse bestätigen', localSupport:'Lokaler Support', supportSubtitle:'Bestellungen, Zahlungen, Lieferungen, Aktionen und Konto.', faqReceived:'Woher weiß ich, ob meine Bestellung eingegangen ist?', faqPayments:'Zahlungen', faqCoupons:'Coupons und Aktionen', faqDelivery:'Lieferungen und Abdeckung', photoGallery:'Fotogalerie', premiumColdCuts:'Premium-Wurstwaren', firstGoal:'Dein erstes Ziel ist es, echte Käufe von 0 bis 24 Punkten zu registrieren.', pollazoFan:'Pollazo-Fan', fromZero:'Ab 0', from25:'Von 25 bis 59 Punkte', currentStatus:'Aktueller Status', checkingLocal:'Das Geschäft prüft Verfügbarkeit, Standort und Zahlungsart.', time:'Zeit', freePlusPayment:'Kostenlose Plus-Zahlung', flour:'Mehl', grains:'Körner', rice:'Reis', wholeChicken:'Ganzes Hähnchen', menudencia:'Innereien' },
  it: { requestReview:'Richiesta in revisione', requestReviewText:'Quando il negozio conferma l’attivazione, l’app si aggiorna in tempo reale.', requestSent:'Richiesta inviata. Il negozio potrà attivare il tuo Plus.', needHelp:'Ho bisogno di aiuto', month:'/ mese', liveIndicators:'Indicatori live di attività e ordini di La Casa del Pollazo.', editingAddress:'Modifica indirizzo', gpsOutside:'Il tuo GPS è fuori da Puerto Ayora', confirmAddress:'Conferma indirizzo', localSupport:'Supporto locale', supportSubtitle:'Ordini, pagamenti, consegne, promozioni e account.', faqReceived:'Come so se il mio ordine è stato ricevuto?', faqPayments:'Pagamenti', faqCoupons:'Coupon e promozioni', faqDelivery:'Consegne e copertura', photoGallery:'Galleria fotografica', premiumColdCuts:'Salumi premium', firstGoal:'Il tuo primo obiettivo è registrare acquisti reali da 0 a 24 punti.', pollazoFan:'Fan Pollazo', fromZero:'Da 0', from25:'Da 25 a 59 punti', currentStatus:'Stato attuale', checkingLocal:'Il locale verifica disponibilità, posizione e forma di pagamento.', time:'Tempo', freePlusPayment:'Pagamento gratis Plus', flour:'Farine', grains:'Grani', rice:'Riso', wholeChicken:'Pollo intero', menudencia:'Interiora' },
  nl: { requestReview:'Aanvraag in beoordeling', requestReviewText:'Wanneer het bedrijf de activering bevestigt, wordt de app realtime bijgewerkt.', requestSent:'Aanvraag verzonden. Het bedrijf kan je Plus activeren.', needHelp:'Ik heb hulp nodig', month:'/ maand', liveIndicators:'Live activiteit- en bestelindicatoren voor La Casa del Pollazo.', editingAddress:'Adres bewerken', gpsOutside:'Je GPS is buiten Puerto Ayora', confirmAddress:'Adres bevestigen', localSupport:'Lokale ondersteuning', supportSubtitle:'Bestellingen, betalingen, leveringen, promoties en account.', faqReceived:'Hoe weet ik of mijn bestelling is ontvangen?', faqPayments:'Betalingen', faqCoupons:'Coupons en promoties', faqDelivery:'Leveringen en dekking', photoGallery:'Fotogalerij', premiumColdCuts:'Premium vleeswaren', firstGoal:'Je eerste doel is echte aankopen van 0 tot 24 punten registreren.', pollazoFan:'Pollazo-fan', fromZero:'Vanaf 0', from25:'Van 25 tot 59 punten', currentStatus:'Huidige status', checkingLocal:'De winkel controleert beschikbaarheid, locatie en betaalmethode.', time:'Tijd', freePlusPayment:'Gratis Plus-betaling', flour:'Meel', grains:'Granen', rice:'Rijst', wholeChicken:'Hele kip', menudencia:'Orgaanvlees' }
};
