-- Phase 6: delivery tracking storage.
-- Non-destructive: prepares the order columns required by secure tracking.

alter table public.orders
  add column if not exists idempotency_key text,
  add column if not exists tracking_token_hash text,
  add column if not exists customer_id uuid,
  add column if not exists payment_status text not null default 'pendiente',
  add column if not exists delivery_fee_original numeric(12,2) not null default 0,
  add column if not exists delivery_fee_final numeric(12,2) not null default 0,
  add column if not exists service_fee numeric(12,2) not null default 0,
  add column if not exists card_fee numeric(12,2) not null default 0,
  add column if not exists membership_applied boolean not null default false,
  add column if not exists membership_id uuid,
  add column if not exists membership_plan text,
  add column if not exists counted_in_metrics boolean not null default false,
  add column if not exists is_test_order boolean not null default false,
  add column if not exists confirmed_at timestamptz,
  add column if not exists delivered_at timestamptz,
  add column if not exists cancelled_at timestamptz,
  add column if not exists cancelled_reason text,
  add column if not exists bonus_items jsonb not null default '[]'::jsonb,
  add column if not exists vip_gift_message text;

create unique index if not exists orders_idempotency_key_unique_idx
  on public.orders (idempotency_key)
  where idempotency_key is not null and btrim(idempotency_key) <> '';

create index if not exists orders_tracking_token_hash_idx
  on public.orders (tracking_token_hash)
  where tracking_token_hash is not null;

create table if not exists public.delivery_devices (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  token_hash text not null unique,
  enabled boolean not null default true,
  max_orders integer not null default 3 check (max_orders between 1 and 8),
  last_seen_at timestamptz,
  current_lat double precision,
  current_lng double precision,
  current_accuracy_m double precision,
  battery_percent integer check (battery_percent is null or battery_percent between 0 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.delivery_sessions (
  id uuid primary key default gen_random_uuid(),
  order_code text not null,
  device_id uuid not null references public.delivery_devices(id) on delete restrict,
  status text not null default 'packing' check (
    status in ('packing', 'en_route', 'nearby', 'arrived', 'delivered', 'cancelled')
  ),
  store_lat double precision not null,
  store_lng double precision not null,
  customer_lat double precision not null,
  customer_lng double precision not null,
  customer_reference text,
  current_lat double precision,
  current_lng double precision,
  current_accuracy_m double precision,
  current_speed_mps double precision,
  current_heading_deg double precision,
  last_captured_at timestamptz,
  departure_streak integer not null default 0,
  nearby_streak integer not null default 0,
  arrival_streak integer not null default 0,
  accepted_samples integer not null default 0,
  rejected_samples integer not null default 0,
  started_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.delivery_locations (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.delivery_sessions(id) on delete cascade,
  latitude double precision not null,
  longitude double precision not null,
  accuracy_m double precision not null,
  speed_mps double precision,
  heading_deg double precision,
  captured_at timestamptz not null,
  created_at timestamptz not null default now()
);

create unique index if not exists delivery_sessions_active_order_unique_idx
  on public.delivery_sessions (order_code)
  where completed_at is null and status not in ('delivered', 'cancelled');

create index if not exists delivery_sessions_device_status_idx
  on public.delivery_sessions (device_id, status, updated_at desc);

create index if not exists delivery_sessions_order_code_idx
  on public.delivery_sessions (order_code, updated_at desc);

create index if not exists delivery_locations_session_time_idx
  on public.delivery_locations (session_id, captured_at desc);

alter table public.delivery_devices enable row level security;
alter table public.delivery_sessions enable row level security;
alter table public.delivery_locations enable row level security;
